version: "3.8"

services:
  # Node.js application
  app:
    image: node-bookstore-app
    ports:
      - "3000:3000" # Correct ports configuration
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=pass123
      - DB_NAME=login
    depends_on:
      - mysql

  # MySQL service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: login
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
